"""restructure_encounters_7_tables

Revision ID: 58b785a471e0
Revises: db253a4df1dc
Create Date: 2026-03-07 18:42:38.850723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58b785a471e0'
down_revision: Union[str, None] = 'db253a4df1dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encounter_diagnoses',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('icd_code', sa.String(length=20), nullable=False),
    sa.Column('icd_description', sa.String(length=500), nullable=False),
    sa.Column('diagnosis_type', sa.String(length=50), nullable=False),
    sa.Column('onset_date', sa.Date(), nullable=True),
    sa.Column('is_chronic_condition', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('added_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_encounter_diagnoses_clinic_id_clinics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], name=op.f('fk_encounter_diagnoses_encounter_id_encounters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_encounter_diagnoses'))
    )
    op.create_index(op.f('ix_encounter_diagnoses_clinic_id'), 'encounter_diagnoses', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_encounter_diagnoses_encounter_id'), 'encounter_diagnoses', ['encounter_id'], unique=False)
    op.create_table('encounter_dispositions',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('disposition_type', sa.String(length=50), nullable=False),
    sa.Column('follow_up_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('follow_up_in_days', sa.Integer(), nullable=True),
    sa.Column('discharge_instructions', sa.Text(), nullable=True),
    sa.Column('activity_restrictions', sa.Text(), nullable=True),
    sa.Column('diet_instructions', sa.Text(), nullable=True),
    sa.Column('patient_education_materials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('discharged_by', sa.UUID(), nullable=True),
    sa.Column('discharged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_encounter_dispositions_clinic_id_clinics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], name=op.f('fk_encounter_dispositions_encounter_id_encounters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_encounter_dispositions'))
    )
    op.create_index(op.f('ix_encounter_dispositions_clinic_id'), 'encounter_dispositions', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_encounter_dispositions_encounter_id'), 'encounter_dispositions', ['encounter_id'], unique=True)
    op.create_table('encounter_medications',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('drug_code', sa.String(length=50), nullable=True),
    sa.Column('drug_name', sa.String(length=255), nullable=False),
    sa.Column('generic_name', sa.String(length=255), nullable=True),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('dosage_unit', sa.String(length=50), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('route', sa.String(length=50), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('is_controlled_substance', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('prescribed_by', sa.UUID(), nullable=True),
    sa.Column('prescribed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_encounter_medications_clinic_id_clinics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], name=op.f('fk_encounter_medications_encounter_id_encounters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_encounter_medications'))
    )
    op.create_index(op.f('ix_encounter_medications_clinic_id'), 'encounter_medications', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_encounter_medications_encounter_id'), 'encounter_medications', ['encounter_id'], unique=False)
    op.create_table('encounter_notes',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=False),
    sa.Column('subjective', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('assessment', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('author_role', sa.String(length=50), nullable=True),
    sa.Column('is_signed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_encounter_notes_clinic_id_clinics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], name=op.f('fk_encounter_notes_encounter_id_encounters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_encounter_notes'))
    )
    op.create_index(op.f('ix_encounter_notes_clinic_id'), 'encounter_notes', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_encounter_notes_encounter_id'), 'encounter_notes', ['encounter_id'], unique=False)
    op.create_table('encounter_orders',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('order_type', sa.String(length=50), nullable=False),
    sa.Column('order_code', sa.String(length=50), nullable=True),
    sa.Column('order_description', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('ordered_by', sa.UUID(), nullable=True),
    sa.Column('ordered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_encounter_orders_clinic_id_clinics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], name=op.f('fk_encounter_orders_encounter_id_encounters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_encounter_orders'))
    )
    op.create_index(op.f('ix_encounter_orders_clinic_id'), 'encounter_orders', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_encounter_orders_encounter_id'), 'encounter_orders', ['encounter_id'], unique=False)
    op.create_table('encounter_vitals',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('blood_pressure_systolic', sa.Integer(), nullable=True),
    sa.Column('blood_pressure_diastolic', sa.Integer(), nullable=True),
    sa.Column('pulse_rate', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('respiratory_rate', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('oxygen_saturation', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('height', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('bmi', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pain_score', sa.Integer(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_encounter_vitals_clinic_id_clinics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], name=op.f('fk_encounter_vitals_encounter_id_encounters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_encounter_vitals'))
    )
    op.create_index(op.f('ix_encounter_vitals_clinic_id'), 'encounter_vitals', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_encounter_vitals_encounter_id'), 'encounter_vitals', ['encounter_id'], unique=False)
    # Add encounter_id as nullable first, backfill, then make NOT NULL
    op.add_column('encounters', sa.Column('encounter_id', sa.String(length=30), nullable=True))
    op.execute(
        "UPDATE encounters SET encounter_id = 'ENC-' || to_char(created_at, 'YYYYMMDD') || '-' || upper(substr(md5(id::text), 1, 4)) WHERE encounter_id IS NULL"
    )
    op.alter_column('encounters', 'encounter_id', nullable=False)
    op.add_column('encounters', sa.Column('provider_id', sa.UUID(), nullable=True))
    op.add_column('encounters', sa.Column('facility_id', sa.UUID(), nullable=True))
    op.add_column('encounters', sa.Column('department_id', sa.UUID(), nullable=True))
    op.add_column('encounters', sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('encounters', sa.Column('triage_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('encounters', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('encounters', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('encounters', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('encounters', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_encounters_encounter_id'), 'encounters', ['encounter_id'], unique=True)
    op.create_index(op.f('ix_encounters_provider_id'), 'encounters', ['provider_id'], unique=False)
    op.create_index(op.f('ix_encounters_scheduled_at'), 'encounters', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_encounters_status'), 'encounters', ['status'], unique=False)
    op.drop_column('encounters', 'weight_kg')
    op.drop_column('encounters', 'lab_orders')
    op.drop_column('encounters', 'prescriptions')
    op.drop_column('encounters', 'examination_notes')
    op.drop_column('encounters', 'height_cm')
    op.drop_column('encounters', 'bp_systolic')
    op.drop_column('encounters', 'bp_diastolic')
    op.drop_column('encounters', 'temperature')
    op.drop_column('encounters', 'completed_at')
    op.drop_column('encounters', 'diagnoses')
    op.drop_column('encounters', 'doctor_name')
    op.drop_column('encounters', 'notes')
    op.drop_column('encounters', 'pulse')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encounters', sa.Column('pulse', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('encounters', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('encounters', sa.Column('doctor_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('encounters', sa.Column('diagnoses', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('encounters', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('encounters', sa.Column('temperature', sa.NUMERIC(precision=4, scale=1), autoincrement=False, nullable=True))
    op.add_column('encounters', sa.Column('bp_diastolic', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('encounters', sa.Column('bp_systolic', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('encounters', sa.Column('height_cm', sa.NUMERIC(precision=5, scale=1), autoincrement=False, nullable=True))
    op.add_column('encounters', sa.Column('examination_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('encounters', sa.Column('prescriptions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('encounters', sa.Column('lab_orders', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('encounters', sa.Column('weight_kg', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_encounters_status'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_scheduled_at'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_provider_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_encounter_id'), table_name='encounters')
    op.drop_column('encounters', 'deleted_at')
    op.drop_column('encounters', 'updated_by')
    op.drop_column('encounters', 'created_by')
    op.drop_column('encounters', 'ended_at')
    op.drop_column('encounters', 'triage_at')
    op.drop_column('encounters', 'checked_in_at')
    op.drop_column('encounters', 'department_id')
    op.drop_column('encounters', 'facility_id')
    op.drop_column('encounters', 'provider_id')
    op.drop_column('encounters', 'encounter_id')
    op.drop_index(op.f('ix_encounter_vitals_encounter_id'), table_name='encounter_vitals')
    op.drop_index(op.f('ix_encounter_vitals_clinic_id'), table_name='encounter_vitals')
    op.drop_table('encounter_vitals')
    op.drop_index(op.f('ix_encounter_orders_encounter_id'), table_name='encounter_orders')
    op.drop_index(op.f('ix_encounter_orders_clinic_id'), table_name='encounter_orders')
    op.drop_table('encounter_orders')
    op.drop_index(op.f('ix_encounter_notes_encounter_id'), table_name='encounter_notes')
    op.drop_index(op.f('ix_encounter_notes_clinic_id'), table_name='encounter_notes')
    op.drop_table('encounter_notes')
    op.drop_index(op.f('ix_encounter_medications_encounter_id'), table_name='encounter_medications')
    op.drop_index(op.f('ix_encounter_medications_clinic_id'), table_name='encounter_medications')
    op.drop_table('encounter_medications')
    op.drop_index(op.f('ix_encounter_dispositions_encounter_id'), table_name='encounter_dispositions')
    op.drop_index(op.f('ix_encounter_dispositions_clinic_id'), table_name='encounter_dispositions')
    op.drop_table('encounter_dispositions')
    op.drop_index(op.f('ix_encounter_diagnoses_encounter_id'), table_name='encounter_diagnoses')
    op.drop_index(op.f('ix_encounter_diagnoses_clinic_id'), table_name='encounter_diagnoses')
    op.drop_table('encounter_diagnoses')
    # ### end Alembic commands ###
